spring.application.name=app
server.port=8080

# SQL Server database from SSMS
# Server: LAPTOP-ALRQJFS1
# Database: LoopCart
spring.datasource.url=jdbc:sqlserver://LAPTOP-ALRQJFS1;databaseName=LoopCart;integratedSecurity=true;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# Keep SQL initialization off because Hibernate will manage tables in development.
spring.sql.init.mode=never

#Default Username
spring.security.user.name=user
spring.security.user.password=12345
